### PR TITLE
add tor example keys

### PR DESCRIPTION
**Pull request by hannob**

### CODE REVIEW

**Comment by BenBE** [comment]
Shouldn't the two keys without a number in their name also get some index added?

**Comment by hannob** [comment]
My filename schema here is:
If a key comes from file foo.c then the key is foo.c.key. If foo.c.key already exists (i.e. either foo.c contains more than 1 key or there are more than 1 foo.c files with a key) I do foo.c.1.key etc.
Did the same for ejbca. I think it doesn't matter that much how to exactly do it, but I can change it if you prefer a different schema.

**Comment by BenBE** [comment]
I'm fine with having filename.c.key with just one key, but I'd prefer that if multiple keys belong into the same file, all should include the numbering. Starting the numbering by zero or one doesn't matter.

**Comment by hannob** [comment]
I pushed another commit to change it to starting with 0.

**Review by BenBE — APPROVED** [review]

**Pull request merged**
