### PR TITLE
Add NIST Public Key Interoperability Test Suite example keys

### PR DESCRIPTION
**Pull request by hannob**

### CODE REVIEW

**Comment by BenBE** [comment]
Seeing these are mostly CA certificate keys, are there matching certificate files for these? If so I'd prefer to also include those.

**Comment by hannob** [comment]
Do you feel this is really necessary?
I can add them, though I feel this is already quite a large number of objects and adding the certs makes things even larger.

**Comment by hannob** [comment]
And I'd like to add in this case it's easy to get the certs from the source and it's unlikely that they'll become inaccessible.

**Comment by BenBE** [comment]
Yes. I prefer to have them included as these will later also be included in the online database for cross-reference. Compared to several other datasets I still have locally including the certificates doesn't add much storage, but provides a benefit IMO.

**Comment by hannob** [comment]
Ok, now with certs.

**Comment by hannob** [comment]
Ok, with the latest commit these are now all example certs and keys from NIST that I found.

**Pull request merged**
