### PR TITLE
openssl test keys

### PR DESCRIPTION
**Pull request by hannob**
This adds keys that are used for testing in the openssl source code.

These are a lot, not vey sorted and with plenty of duplicates. I ended up saving them in filenames based on the md5 hash of their public key in order to avoid duplicates and also make it easier to add more alike and filter out duplicates (i.e. I want to add test keys from other software projects later, but I want an easy way to avoid adding keys that are just re-used among multiple tes suites).

### CODE REVIEW

**Comment by BenBE** [comment]
I agree with the basic idea and IMO using the public key fingerprint for naming is a good idea.

Just two ideas for changes:
1. Drop the version number from the directory as those keys have likely been there for much longer and aren't specific to that version
2. Instead of the exact version tarball pointing to the (Git) sources on GH might be a better option which would also cover previous and upcoming versions.

**Comment by hannob** [comment]
The reason I added the version is that apparently there are some keys in older versions that aren't part of the current version.
So my idea was having the version in the dirname gives you at least a better idea where to look for those keys.

But if you prefer I can skip that and we throw all keys in one dir (maybe that's even better because having an openssl-3.0.0 dir with lots of keys, then an openssl-1.1.1 dir with very few keys might be a bit odd). Would mean someone tracing back a key might have to look further than only the current version, but we can mention that in the description.

**Comment by BenBE** [comment]
ACK regarding the tracing. But unless we do a full split between all releases like with the RFCs/drafts (where I see this makes sense) it's probably easier to just combine those parts. You still could do a naming scheme similar to what I did with the Debian OpenSSL RNG Debacle keys and include the first-seen release version in the filename, but IMHO that's overkill.

So just having one directory per project is totally fine with me.

**Comment by hannob** [comment]
Updated the pullrequest.

**Pull request merged**
